### ISSUE TITLE
builds does not exist and probably cannot be created

### ISSUE THREAD

**Issue by devgraphy** [devgraphy/JenkinsTest#2]
https://dzone.com/articles/jenkins-02-changing-home-directory
위의 설명대로 jenkins home을 변경한 후에 다음과 같은 이슈가 발생하였다. jenkins 사이트가 접속이 되지 않는다.
```
jenkins.model.InvalidBuildsDir: ${ITEM_ROOTDIR}/builds does not exist and probably cannot be created
	at jenkins.model.Jenkins.checkRawBuildsDir(Jenkins.java:3316)
	at jenkins.model.Jenkins.loadConfig(Jenkins.java:3238)
Caused: java.io.IOException
	at jenkins.model.Jenkins.loadConfig(Jenkins.java:3241)
	at jenkins.model.Jenkins.access$1200(Jenkins.java:340)
	at jenkins.model.Jenkins$12.run(Jenkins.java:3336)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1160)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:50)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1193)
	at jenkins.model.Jenkins.<init>(Jenkins.java:991)
	at hudson.model.Hudson.<init>(Hudson.java:86)
	at hudson.model.Hudson.<init>(Hudson.java:82)
	at hudson.WebAppMain$3.run(WebAppMain.java:298)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:315)
```

**Comment by devgraphy** [comment]
jenkins 사용자가 변경된 JENKINS_HOME에 대한 권한이 있지 않아 접근 권한의 문제가 발생하였다.
아래 명령어를 실행하여 jenkins 디렉터리에 대한 소유자를 변경해준다.
`sudo chmod -R jenkins:jenkins $JENKINS_HOME`

소유자를 변경해주어도 같은 에러가 발생할 경우, 시스템 reboot를 실행한다.

[소유자 변경](https://stackoverflow.com/questions/50798720/jenkins-throwing-error-jenkins-model-invalidbuildsdir-item-rootdir-builds-d)
[환경변수 수정](https://linuxtechlab.com/simple-way-to-change-home-directory-of-jenkins-server/)

**Comment by devgraphy** [comment]
시스템 정보에는 환경 변수로 `HOME`과 `JENKINS_HOME` 가 있다.
HOME은 usermod라는 사용자 계정 정보를 변경하는 명령어로 바꿀 수 있다.
`usermod -d <홈 디렉터리로 지정할 경로> <계정명>`
`JENKINS_HOME`은 /etc/default/jenkins에서 변경한다.
